<script>

let user = {
    name: "Джон",
    go: function() { alert(this.name) }
}

(user.go)() // из-за того, что опущены ';' и выражение в круглых скобках,
            // данная строка засчитывается как продолжение после фигурных скобок объекта,
            // в результате она является вызовом функции с аргументом 'user.go',
            // а 'user' ещё не инициализирован в момент вызова, что создаёт ошибку.

</script>
